/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function YLogo(props) {
   const { nodes, materials } = useGLTF("models/YESCA-LOGO-MAIN.glb");
   const roughness = 0.5;
   const mat = 0.5;

   return (
      <group {...props} dispose={null}>
         <mesh
            visible={false}
            castShadow
            receiveShadow
            geometry={nodes["3DGeom-1"].geometry}
            // material={materials["*1"]}
            position={[5.507, 3.985, -0.2]}
         ></mesh>
         <mesh
            castShadow
            receiveShadow
            geometry={nodes["3DGeom-2"].geometry}
            // material={nodes["3DGeom-2"].material}
            position={[-9.244, 23.449, 0]}
         >
            <meshStandardMaterial color={"#2e3192"} roughness={roughness} metalness={mat} />
         </mesh>
         <mesh
            castShadow
            receiveShadow
            geometry={nodes["3DGeom-3"].geometry}
            // material={nodes["3DGeom-3"].material}
            position={[-3.694, 5.248, 0]}
         >
            <meshStandardMaterial
               color={"#2e3192"}
               side={THREE.DoubleSide}
               roughness={roughness}
               metalness={mat}
            />
         </mesh>
         <mesh
            visible={false}
            castShadow
            receiveShadow
            geometry={nodes["3DGeom-4"].geometry}
            material={materials["*2"]}
            position={[-12, 0, -2]}
         />
      </group>
   );
}

useGLTF.preload("models/YESCA-LOGO-MAIN.glb");
