import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./Components/Header";
import gsap from "gsap";
import { Roboto_Condensed, Poppins } from "next/font/google";
import Footer from "./(SECTIONS)/Footer";

const robotoCondensed = Roboto_Condensed({
  weight: "700", // Black
  style: "italic",
  subsets: ["latin"],
  variable: "--font-roboto-condensed",
});

const poppins = Poppins({
  weight: "400", // Regular
  subsets: ["latin"],
  variable: "--font-poppins",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//    title: "YESCA",
//    description: "Generated by create next app",
//    icons: {
//       icon: "/images/YESCA.svg",
//    },
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>yesca.in</title>
      <link rel="icon" type="image/favicon" href="/images/YESCA.svg" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {/* Door panels */}
        {/* <div ref={leftDoor} className="door left hidden md:flex">
          <img
            ref={Y}
            src="/LattersSvg/Y.svg"
            alt="Y"
            className="left-door-img"
          />
        </div>

        <div ref={rightDoor} className="door right hidden md:flex">
          <img
            ref={Dot}
            src="/LattersSvg/Dot.svg"
            alt="Dot"
            className="right-door-img"
          />
        </div> */}
        {children}

        <Footer />
      </body>
    </html>
  );
}
